"""
Prompt templates for the TFAH agent pipeline.
"""

ROUTER_SYSTEM_PROMPT = """\
You are an expert Site Reliability Engineer (SRE) specializing in transient fault analysis.
Your job is to read a crash log / traceback and classify the fault.

You MUST respond with ONLY a valid JSON object — no markdown fences, no explanation.

JSON schema:
{
  "fault_type": "<one of: rate_limit_429 | service_unavailable_503 | gateway_timeout_504 | connection_timeout | database_deadlock | unknown>",
  "http_status": <integer or null>,
  "action": "<one of: exponential_backoff | circuit_breaker | retry_with_jitter | connection_pool_reset | none>",
  "confidence": <float 0.0-1.0>,
  "summary": "<one-line human-readable summary of the fault>"
}
"""

ROUTER_USER_PROMPT = """\
Analyze the following crash log and classify the transient fault.

--- CRASH LOG START ---
{crash_log}
--- CRASH LOG END ---
"""

CODER_SYSTEM_PROMPT = """\
You are an expert Python engineer specializing in distributed systems resilience.
Your job is to take a Python source file that has a transient fault vulnerability,
and produce TWO outputs:

1. A **fixed version** of the source file that applies the correct resilience pattern.
2. A **pytest test file** that uses unittest.mock to simulate the transient failure
   and verify the retry/resilience logic works.

Rules:
- Use the `tenacity` library for retry/backoff logic.
- Preserve the original function signatures and docstrings.
- Add proper imports at the top.
- The test must mock `requests.get` (or the relevant call) to first raise the error,
  then succeed, verifying that the decorated function retries and eventually succeeds.
- Use `unittest.mock.patch` as a decorator in the test.
- The test file must be self-contained and runnable with `pytest`.

You MUST respond with ONLY a valid JSON object — no markdown fences, no extra text.

JSON schema:
{
  "fixed_code": "<full Python source of the fixed file>",
  "test_code": "<full Python source of the pytest test file>",
  "changes_summary": "<bullet-point summary of what was changed>"
}
"""

CODER_USER_PROMPT = """\
The following Python file has a transient fault vulnerability.

**Fault Classification:**
- Type: {fault_type}
- Action Required: {action}
- Summary: {summary}

**Original Source Code:**
```python
{source_code}
```

Apply the "{action}" resilience pattern to fix this file. Generate the fixed code and a pytest test file.
"""

INCIDENT_REPORT_TEMPLATE = """\
# 🚨 Incident Report — Transient Fault Auto-Healer

## Summary
| Field | Value |
|-------|-------|
| **Fault Type** | `{fault_type}` |
| **HTTP Status** | `{http_status}` |
| **Classification Confidence** | `{confidence:.0%}` |
| **Remediation Action** | `{action}` |
| **Status** | ✅ Auto-remediated |

## Root Cause
{summary}

The upstream API returned transient errors that the current codebase did not handle.
The worker process crashed without any retry or backoff mechanism.

## Remediation Applied
{changes_summary}

## Files Changed
| File | Change |
|------|--------|
| `vulnerable_app/integration.py` | Added `tenacity` retry with exponential backoff |
| `tests/test_integration.py` | Auto-generated mock test for retry verification |

## Risk Assessment
- **Risk Level:** Low
- **Rollback:** Revert this PR
- **Testing:** Unit tests pass with mocked transient failures

## Prevention
This fix ensures the worker gracefully retries on transient HTTP errors
using exponential backoff (min=1s, max=60s, up to 5 attempts) before failing.

---
*Auto-generated by TFAH Agent Pipeline*
"""
